### ISSUE TITLE
error -1: createnewblock: testblockvalidity failed: mweb-connect-failed, mweb::node::connectblock(): failed to connect mweb block: pedersencommitsum: secp256k1_pedersen_commit_sum error

### ISSUE THREAD

**Issue by goodthebest** [litecoin-project/litecoin#1006]
Ver: litecoin-0.21.4

```error -1: createnewblock: testblockvalidity failed: mweb-connect-failed, mweb::node::connectblock(): failed to connect mweb block: pedersencommitsum: secp256k1_pedersen_commit_sum error```

**Comment by zlausd** [comment]
Observed this is well. It resolved itself after roughly one hour.

**Comment by jplix7k** [comment]
We also suffered from this error, mining was totally stopped during that time. Wondering if it is caused by one block and fixed by another one.

**Comment by burkesbi** [comment]
Same here, just spent the last hour trying to work out WTF was going on. Looks like the mempool spiked massively and it seems like only F2Pool was able to mine blocks during that time. :(

**Comment by zlausd** [comment]
Some extra data. This started around 14:10 UTC and was resolved by around 15:05UTC.

**Comment by burkesbi** [comment]
> According to my logs, the same error was reported on Feb 05 between 19:51:37 UTC and 19:53:40 UTC Seems like a bug in 0.21.4, at least with a source compiled on clean Ubuntu 24.04
We're running 0.21.2 so it's going back further than that I'm afraid. :(

**Comment by zlausd** [comment]
Ditto, was running 0.21.2 as well, upgraded to 0.21.4 but issue remained.

**Comment by losh11** [comment]
@goodthebest why did you close this issue?

**Comment by goodthebest** [comment]
@losh11 because the issue is resolved at my end.

**Comment by losh11** [comment]
How did you fix the issue?

**Comment by goodthebest** [comment]
It just disappeared itself within an hour and everything is back to normal. 

Did you get any clue?

**Comment by DavidBurkett** [comment]
Do any of you still have logs that you're willing to share? I'm thinking it may have been a particular transaction or set of transactions in the mempool that your nodes were attempting to include in a block, but were causing it to be invalid. Knowing exactly when it started occurring, and more importantly, at which block it stopped occurring, would be helpful in identifying those transactions.

**Comment by cotinco** [comment]
My node list the first instance of the problem at 14:11:15 UTC and the last one at 15:05:52 UTC (during Feb 07 interval)
15:05:55 UTC is the time when the block 2841351 was received, it lowered the "MWEB weight" value, probably it included some transaction that caused the problem
14:11:15 UTC is the time when the block 2841339 was received
Also there was a window between 14:38:12 UTC and 14:40:46 UTC when the templates were generated correctly
14:40:46 UTC is the time of block 2841346
14:38:12 UTC has no specific block associated, but MWEB weight in the log grew at that point:
2025-02-07T14:38:12Z CreateNewBlock(): block weight: 3747887 txs: 2121 fees: 9707537 sigops: 11527 MWEB weight: 26
2025-02-07T14:38:14Z CreateNewBlock(): block weight: 3759359 txs: 2131 fees: 9734128 sigops: 11564 MWEB weight: 65
2025-02-07T14:38:20Z CreateNewBlock(): block weight: 3771098 txs: 2146 fees: 9821850 sigops: 11606 MWEB weight: 104 

On Feb 05, the problem cleared with block 2840302 at 19:53:43 UTC
and initiated also at a point where just MWEB weight grew:
2025-02-05T19:51:31Z CreateNewBlock(): block weight: 938527 txs: 918 fees: 4331645 sigops: 4051 MWEB weight: 21
2025-02-05T19:51:37Z CreateNewBlock(): block weight: 957013 txs: 941 fees: 4473344 sigops: 4114 MWEB weight: 25

**Comment by jplix7k** [comment]
This is our case. Issue appeared just after litecoind updated to block 2841339 but disappeared at block 2841350. There are several minutes time difference between UpdateTip of 2841350 and last error and UpdateTip of 2841351. 

### 1st error
2025-02-07T14:11:15Z UpdateTip: new best=2d0c93ff44da7b5d7605a4eede43ff40cdb89cbb5933f4284889a3ccb7e0d6f7 height=2841339 version=0x20000014 log2_work=76.576967 tx=306199847 date='2025-02-07T14:10:49Z' progress=1.000000 cache=23.8MiB(138569txo)
2025-02-07T14:11:15Z CreateNewBlock(): block weight: 1032725 txs: 260 fees: 914398 sigops: 3388 MWEB weight: 26
E0207 14:11:15.731117] rpc call fail: {"result":null,"error":{"code":-1,"message":"CreateNewBlock: TestBlockValidity failed: mweb-connect-failed, MWEB::Node::ConnectBlock(): Failed to connect MWEB block: PedersenCommitSum: secp256k1_pedersen_commit_sum error"},"id":"1"}

### last error
**2025-02-07T15:02:06Z** UpdateTip: new best=db6d60f1b8de40770ce9b36475cf06c62188ca4c554b36d1487c41b6a97f84f9 height=**2841350** version=0x20000014 log2_work=76.577012 tx=306206437 date='2025-02-07T15:01:32Z' progress=1.000000 cache=2.7MiB(20450txo)

**2025-02-07T15:05:55Z** CreateNewBlock(): block weight: 3993080 txs: 1686 fees: 7174741 sigops: 24226 MWEB weight: 26
E0207 15:05:55.079128] rpc call fail: {"result":null,"error":{"code":-1,"message":"CreateNewBlock: TestBlockValidity failed: mweb-connect-failed, MWEB::Node::ConnectBlock(): Failed to connect MWEB block: PedersenCommitSum: secp256k1_pedersen_commit_sum error"},"id":"1"}
2025-02-07T15:05:56Z CreateNewBlock(): block weight: 3993115 txs: 1689 fees: 7187216 sigops: 24230 MWEB weight: 65
I0207 15:05:56.212323] height: 2841351, prev_hash: db6d60f1b8de40770ce9b36475cf06c62188ca4c554b36d1487c41b6a97f84f9, ...

**2025-02-07T15:07:16Z** UpdateTip: new best=2c227385e43d6905a88f2fccc24928b081f9869df19751df2b970ff4f49639cf height=**2841351** version=0x20000000 log2_work=76.577017 tx=306208131 date='2025-02-07T15:05:57Z' progress=1.000000 cache=3.4MiB(26156txo)

**Comment by jplix7k** [comment]
This is the log when same error occurred on 6th Feb.

### 1st error
2025-02-05T19:51:28Z CreateNewBlock(): block weight: 928160 txs: 906 fees: 4309802 sigops: 4017 MWEB weight: 21
I0205 19:51:28.165647  ] height: 2840302, prev_hash: 2774ecd650d7f4935254c40ce19ff3ca71d295f7f454fb3b6f0a68cc031b378e, ...
2025-02-05T19:51:38Z CreateNewBlock(): block weight: 959489 txs: 944 fees: 4475903 sigops: 4116 MWEB weight: 25
E0205 19:51:38.237023 ] rpc call fail: {"result":null,"error":{"code":-1,"message":"CreateNewBlock: TestBlockValidity failed: mweb-connect-failed, MWEB::Node::ConnectBlock(): Failed to connect MWEB block: PedersenCommitSum: secp256k1_pedersen_commit_sum error"},"id":"1"}

### last error
2025-02-05T19:53:42Z CreateNewBlock(): block weight: 1315871 txs: 1234 fees: 5532214 sigops: 5596 MWEB weight: 25
E0205 19:53:42.971956 ] rpc call fail: {"result":null,"error":{"code":-1,"message":"CreateNewBlock: TestBlockValidity failed: mweb-connect-failed, MWEB::Node::ConnectBlock(): Failed to connect MWEB block: PedersenCommitSum: secp256k1_pedersen_commit_sum error"},"id":"1"}
2025-02-05T19:53:43Z UpdateTip: new best=5b6c68fe9bed6c7290393592485b09fc738bd0757e92a9e06a2b42cf0de31874 height=2840302 version=0x20000000 log2_work=76.572673 tx=305867392 date='2025-02-05T19:50:09Z' progress=0.999999 cache=29.2MiB(182624txo)
2025-02-05T19:53:43Z CreateNewBlock(): block weight: 609782 txs: 544 fees: 1945982 sigops: 2831 MWEB weight: 4
I0205 19:53:43.378425] height: 2840303, prev_hash: 5b6c68fe9bed6c7290393592485b09fc738bd0757e92a9e06a2b42cf0de31874, ...

**Comment by jplix7k** [comment]
Issue occurred again on 11th Feb. MWEB weight sticked to 25 from the start to the end. I guess it means mweb transactions in block template remained same. And looks like fix is triggered by changing the combination?(weight is increased from 25 to 47) 

### Start
2025-02-11T11:03:19Z UpdateTip: new best=ccc2b24e12071228f9fb2835ed702bf13398f30ab6fef6bf7b8d642a4c380cc3 height=**2843621** version=0x20000014 log2_work=76.586450 tx=306954869 date='2025-02-11T11:03:06Z' progress=1.000000 cache=35.8MiB(265056txo)

2025-02-11T11:03:19Z CreateNewBlock(): block weight: 160451 txs: 80 fees: 145663 sigops: 1175 MWEB weight: **25** **<--first error**

2025-02-11T11:06:26Z UpdateTip: new best=2008dae992c207e4c69dafbb78465cbd15fa88241935ac00349e2bfbab04a572 height=**2843622** version=0x20000014 log2_work=76.586454 tx=306955199 date='2025-02-11T11:05:41Z' progress=1.000000 cache=35.8MiB(265501txo)

###End
2025-02-11T11:06:54Z CreateNewBlock(): block weight: 279298 txs: 236 fees: 377951 sigops: 1693 MWEB weight: **25** **<--last error**

2025-02-11T11:06:55Z CreateNewBlock(): block weight: 279987 txs: 237 fees: 381353 sigops: 1694 MWEB weight: 47

**Comment by goodthebest** [comment]
@jplix7k I noticed MWEB weight 0 in latest logs, can you please confirm if your latest log getting any MWEB weight value or it's zero too?

2025-03-01T04:30:38Z CreateNewBlock(): block weight: 1525745 txs: 797 fees: 4187333 sigops: 5939 MWEB weight: 0
2025-03-01T04:31:00Z CreateNewBlock(): block weight: 1602264 txs: 831 fees: 4313419 sigops: 6203 MWEB weight: 0
2025-03-01T04:31:21Z CreateNewBlock(): block weight: 1632846 txs: 865 fees: 4416361 sigops: 6308 MWEB weight: 0
2025-03-01T04:31:40Z CreateNewBlock(): block weight: 1686852 txs: 894 fees: 4499434 sigops: 6500 MWEB weight: 0
2025-03-01T04:32:04Z CreateNewBlock(): block weight: 1772892 txs: 930 fees: 4551905 sigops: 6794 MWEB weight: 0
2025-03-01T04:32:26Z CreateNewBlock(): block weight: 1840082 txs: 972 fees: 4619546 sigops: 7088 MWEB weight: 0
2025-03-01T04:32:40Z CreateNewBlock(): block weight: 1867466 txs: 1003 fees: 4687808 sigops: 7184 MWEB weight: 0
2025-03-01T04:32:47Z CreateNewBlock(): block weight: 1876421 txs: 1014 fees: 4701825 sigops: 7218 MWEB weight: 0
2025-03-01T04:33:08Z CreateNewBlock(): block weight: 1936018 txs: 1049 fees: 4787189 sigops: 7422 MWEB weight: 0
2025-03-01T04:33:30Z CreateNewBlock(): block weight: 2015055 txs: 1079 fees: 4852176 sigops: 7731 MWEB weight: 0
2025-03-01T04:33:41Z CreateNewBlock(): block weight: 2103725 txs: 1103 fees: 5522909 sigops: 8011 MWEB weight: 0
2025-03-01T04:33:52Z CreateNewBlock(): block weight: 2121883 txs: 1125 fees: 5561469 sigops: 8092 MWEB weight: 0
2025-03-01T04:33:52Z Potential stale tip detected, will try using extra outbound peer (last tip update: 590 seconds ago)
2025-03-01T04:33:53Z New outbound peer connected: version: 70017, blocks=2853872, peer=16 (full-relay)
2025-03-01T04:34:00Z New outbound peer connected: version: 70016, blocks=2853872, peer=17 (full-relay)
2025-03-01T04:34:06Z New outbound peer connected: version: 70017, blocks=2853872, peer=18 (full-relay)
2025-03-01T04:34:13Z CreateNewBlock(): block weight: 2216415 txs: 1169 fees: 5636478 sigops: 8484 MWEB weight: 0
2025-03-01T04:34:34Z CreateNewBlock(): block weight: 2333517 txs: 1221 fees: 5774217 sigops: 8886 MWEB weight: 0
2025-03-01T04:34:40Z CreateNewBlock(): block weight: 2396135 txs: 1232 fees: 5800767 sigops: 9113 MWEB weight: 0
2025-03-01T04:34:53Z CreateNewBlock(): block weight: 2414557 txs: 1259 fees: 5905045 sigops: 9159 MWEB weight: 0
2025-03-01T04:35:05Z CreateNewBlock(): block weight: 2427244 txs: 1275 fees: 6025498 sigops: 9204 MWEB weight: 0
2025-03-01T04:35:17Z CreateNewBlock(): block weight: 2499569 txs: 1304 fees: 6129076 sigops: 9494 MWEB weight: 0
2025-03-01T04:35:39Z CreateNewBlock(): block weight: 2590303 txs: 1338 fees: 6289048 sigops: 9876 MWEB weight: 0

**Comment by jplix7k** [comment]
@goodthebest Yeah, I can observe same phenomenon. But looks like it exists from long time ago with same frequency, at least since January this year base on log record.

**Comment by cotinco** [comment]
Again, there is the same problem since 09:40:06 UTC today (block 2864429)
Until now still not fixed
--daemon log--
2025-03-19T09:40:04Z CreateNewBlock(): block weight: 678446 txs: 327 fees: 2228714 sigops: 2772 MWEB weight: 103
2025-03-19T09:40:06Z UpdateTip: new best=39f929a3729b6c30862d5e98b2c1b241eac31bbbd80ba5c7215f70bf54b3c5c0 height=2864429 version=0x20000014 log2_work=76.674706 tx=313936352 date='2025-03-19T09:39:31Z' progress=1.000000 cache=24.5MiB(156113txo)
2025-03-19T09:40:06Z CreateNewBlock(): block weight: 427666 txs: 98 fees: 289810 sigops: 1950 MWEB weight: 25
... repeats many times ...
2025-03-19T09:57:01Z CreateNewBlock(): block weight: 1748881 txs: 899 fees: 4812753 sigops: 6943 MWEB weight: 25
--pool log--
2025-03-19 09:40:06.207 getblocktemplate for coin LTC call failed for daemon instance 0 with error {"code":-1,"message":"CreateNewBlock: TestBlockValidity failed: mweb-connect-failed, MWEB::Node::ConnectBlock(): Failed to connect MWEB block: PedersenCommitSum: secp256k1_pedersen_commit_sum error"}
... repeats many times ...
2025-03-19 09:57:01.954 getblocktemplate for coin LTC call failed for daemon instance 0 with error {"code":-1,"message":"CreateNewBlock: TestBlockValidity failed: mweb-connect-failed, MWEB::Node::ConnectBlock(): Failed to connect MWEB block: PedersenCommitSum: secp256k1_pedersen_commit_sum error"}

**Comment by burkesbi** [comment]
Just adding a "same for us; broken again" comment too. Still investigating logs to see if it's identical as before. :(

**Comment by zlausd** [comment]
Ditto, identical as before from my end.

**Comment by cotinco** [comment]
Another interesting thing is, that after getting block 2864433, which probably resolved the situation, the daemon was not responsible for 18 (!!!) seconds. Is mweb such a slow thing?

**Comment by kings-yao** [comment]
I have same error in version 0.21.4,Calling getblocktemplate returns a 500 error. Opening the debug log, I found that the exception occurred in the function MWEB::Node::ConnectBlock. The debug log is as follows:

2025-03-19T10:06:56.866769Z CreateNewBlock(): block weight: 1497180 txs: 1097 fees: 12947331 sigops: 6127 MWEB weight: 25
2025-03-19T10:06:56.868778Z     - Sanity checks: 0.42ms [0.39s (0.49ms/blk)]
2025-03-19T10:06:56.868822Z     - Fork checks: 0.05ms [0.04s (0.04ms/blk)]
2025-03-19T10:06:56.873392Z       - Connect 1099 transactions: 4.57ms (0.004ms/tx, 0.002ms/txin) [3.64s (4.51ms/blk)]
2025-03-19T10:06:56.873411Z     - Verify 2920 txins: 4.60ms (0.002ms/txin) [3.66s (4.54ms/blk)]
2025-03-19T10:06:56.902214Z sending inv (37 bytes) peer=16
2025-03-19T10:06:56.902315Z received: ping (8 bytes) peer=134
2025-03-19T10:06:56.902333Z sending pong (8 bytes) peer=134
2025-03-19T10:06:56.938077Z received: tx (284 bytes) peer=5

From the log, it can be seen that the log after "- Verify" is missing
